-- sui_i18n.lua — Simple UI
-- Translation loader.
--
-- DESIGN (v2 — isolated proxy, no global monkey-patch)
-- =====================================================
-- The previous approach replaced package.loaded["gettext"] with a wrapper
-- table that only had __index (read delegation) but no __newindex.  This
-- caused a silent state-mutation bug: when another plugin (e.g. zlibrary)
-- temporarily wrote to a gettext field to load its own .po files, the write
-- landed on the wrapper and never reached the native module.  The native
-- gettext then failed to find its translations entirely.
--
-- The fix is straightforward: do NOT touch the global module cache at all.
-- Instead, export a self-contained translate() / ngettext() pair that each
-- simpleui module uses directly as its local `_` / `N_`.
--
-- Public API:
--   local I18n = require("sui_i18n")
--   local _    = I18n.translate    -- replaces: local _ = require("gettext")
--   local N_   = I18n.ngettext     -- replaces: local N_ = _.ngettext
--   I18n.getLang()                 -- still works
--   I18n.reset()                   -- clears cached translations
--
-- Strings not found in simpleui's .po files fall through to the native
-- gettext, so KOReader's own UI strings continue to work correctly.
--
-- HOW TO ADD A LANGUAGE
--   1. Copy locale/simpleui.pot -> locale/<lang>.po  (e.g. locale/de.po)
--   2. Fill in the msgstr values.
--   3. Done — no code changes needed.

local logger = require("logger")

-- Locate the plugin directory from this file's path.
local _dir = (debug.getinfo(1, "S").source:match("^@(.+/)") or "./")

-- ---------------------------------------------------------------------------
-- .po parser — minimal, handles the subset generated by simpleui.pot
-- ---------------------------------------------------------------------------
local function parsePluralExpression(expr)
    local function translateTernary(s)
        local function findQuestion(str)
            local depth = 0
            for i = 1, #str do
                local c = str:sub(i, i)
                if c == "(" then
                    depth = depth + 1
                elseif c == ")" then
                    depth = depth - 1
                elseif c == "?" and depth == 0 then
                    return i
                end
            end
            return nil
        end

        local q = findQuestion(s)
        if not q then
            return s
        end

        local depth = 0
        local colon = nil
        for i = q + 1, #s do
            local c = s:sub(i, i)
            if c == "(" then
                depth = depth + 1
            elseif c == ")" then
                depth = depth - 1
            elseif c == ":" and depth == 0 then
                colon = i
                break
            end
        end

        if not colon then
            return s
        end

        local cond   = s:sub(1, q - 1)
        local truthy = s:sub(q + 1, colon - 1)
        local falsy  = s:sub(colon + 1)
        return "(" .. translateTernary(cond) .. " and (" .. translateTernary(truthy) .. ") or (" .. translateTernary(falsy) .. "))"
    end

    expr = expr:gsub("!=",   "~=")
    expr = expr:gsub("&&",   " and ")
    expr = expr:gsub("%|%|", " or ")
    expr = expr:gsub("!%s*", "not ")
    expr = translateTernary(expr)

    local loadfunc = loadstring or load
    local fn, _err = loadfunc("return function(n) return " .. expr .. " end")
    if not fn then return nil end

    local ok, pluralFn = pcall(fn)
    if not ok or type(pluralFn) ~= "function" then return nil end
    return pluralFn
end

local function parsePO(path)
    local f = io.open(path, "r")
    if not f then return nil end

    local map        = {}
    local pluralizer = nil
    local entry      = { msgid = nil, msgid_plural = nil, msgstrs = {} }
    local current_field = nil

    local function flush()
        if not entry.msgid then
            entry         = { msgid = nil, msgid_plural = nil, msgstrs = {} }
            current_field = nil
            return
        end

        if entry.msgid == "" then
            local header = entry.msgstrs[0] or ""
            for line in header:gmatch("([^\n]*)\n?") do
                local plural_line = line:match("^Plural%-Forms:%s*(.-)%s*$")
                if plural_line then
                    pluralizer = parsePluralExpression(plural_line)
                    break
                end
            end
        else
            if entry.msgid_plural then
                local trans = {}
                for idx, str in pairs(entry.msgstrs) do
                    if str and str ~= "" then trans[idx] = str end
                end
                if next(trans) then map[entry.msgid] = trans end
            else
                local str = entry.msgstrs[0]
                if str and str ~= "" then map[entry.msgid] = str end
            end
        end

        entry         = { msgid = nil, msgid_plural = nil, msgstrs = {} }
        current_field = nil
    end

    local function unescape(s)
        return s:gsub("\\n", "\n"):gsub("\\t", "\t"):gsub('\\"', '"'):gsub("\\\\", "\\")
    end

    for line in f:lines() do
        local text = line:match("^%s*(.-)%s*$")
        if text == "" then
            flush()
        elseif text:match("^#") then
            -- ignore comments
        elseif text:match('^msgid%s+"') then
            flush()
            entry.msgid = unescape(text:match('^msgid%s+"(.*)"') or "")
            current_field = "msgid"
        elseif text:match('^msgid_plural%s+"') then
            entry.msgid_plural = unescape(text:match('^msgid_plural%s+"(.*)"') or "")
            current_field = "msgid_plural"
        elseif text:match('^msgstr%[%d+%]%s+"') then
            local idx = tonumber(text:match('^msgstr%[(%d+)%]%s+"'))
            entry.msgstrs[idx] = unescape(text:match('^msgstr%[%d+%]%s+"(.*)"') or "")
            current_field = "msgstr" .. idx
        elseif text:match('^msgstr%s+"') then
            entry.msgstrs[0] = unescape(text:match('^msgstr%s+"(.*)"') or "")
            current_field = "msgstr0"
        elseif text:match('^"') and current_field then
            local cont = unescape(text:match('^"(.*)"') or "")
            if current_field == "msgid" then
                entry.msgid = entry.msgid .. cont
            elseif current_field == "msgid_plural" then
                entry.msgid_plural = entry.msgid_plural .. cont
            else
                local idx = tonumber(current_field:match("^msgstr(%d+)$"))
                if idx then
                    entry.msgstrs[idx] = (entry.msgstrs[idx] or "") .. cont
                end
            end
        end
    end
    flush()
    f:close()
    return map, pluralizer
end

-- ---------------------------------------------------------------------------
-- Language detection
-- ---------------------------------------------------------------------------
local function detectLang()
    local lang = G_reader_settings and G_reader_settings:readSetting("language")
    if type(lang) == "string" and lang ~= "" then return lang end
    local lc = os.getenv("LANG") or os.getenv("LC_ALL") or os.getenv("LC_MESSAGES") or ""
    lang = lc:match("^([a-zA-Z_]+)")
    return lang or "en"
end

-- ---------------------------------------------------------------------------
-- Load translation table (lazy, cached)
-- ---------------------------------------------------------------------------
local _translations = nil
local _loaded       = false

local function loadTranslations()
    if _loaded then return _translations end
    _loaded = true

    local lang = detectLang()
    if lang == "en" or lang:match("^en_") then return nil end

    local function try(name)
        local path = _dir .. "locale/" .. name .. ".po"
        local entries, pluralizer = parsePO(path)
        if entries and next(entries) then
            local n = 0; for _ in pairs(entries) do n = n + 1 end
            logger.info("simpleui i18n: loaded " .. path .. " — " .. n .. " strings")
            return { entries = entries, plural = pluralizer }
        end
    end

    _translations = try(lang) or (function()
        local prefix = lang:match("^([a-zA-Z]+)")
        if prefix and prefix ~= lang then return try(prefix) end
    end)()

    return _translations
end

-- ---------------------------------------------------------------------------
-- Core translation functions.
--
-- Each simpleui module does:
--   local _  = require("sui_i18n").translate
--   local N_ = require("sui_i18n").ngettext
--
-- Strings absent from simpleui's catalogue fall through to the native
-- KOReader gettext without writing to or wrapping package.loaded["gettext"].
-- ---------------------------------------------------------------------------

local function translate(msgid)
    local t = loadTranslations()
    if t then
        local entry = t.entries[msgid]
        if type(entry) == "string" then
            return entry
        elseif type(entry) == "table" then
            return entry[0] or entry[1] or msgid
        end
    end
    -- Read-only access to native gettext — no writes, no state mutation.
    local ok, gt = pcall(require, "gettext")
    if ok and gt then return gt(msgid) end
    return msgid
end

local function ngettext(msgid, msgid_plural, n)
    local t = loadTranslations()
    if t then
        local entry = t.entries[msgid]
        if type(entry) == "table" then
            local idx = 0
            if t.plural then
                idx = t.plural(n) or 0
            else
                idx = (n == 1) and 0 or 1
            end
            local translated = entry[idx]
            if translated then return translated end
        elseif type(entry) == "string" and n == 1 then
            return entry
        end
    end
    -- Fall through to native gettext.
    local ok, gt = pcall(require, "gettext")
    if ok and gt then
        if type(gt) == "table" and type(gt.ngettext) == "function" then
            return gt.ngettext(msgid, msgid_plural, n)
        end
        local fallback = (n == 1) and msgid or msgid_plural
        return gt(fallback)
    end
    return (n == 1) and msgid or msgid_plural
end

-- ---------------------------------------------------------------------------
-- reset() — clears cached translations (e.g. after a language change).
-- ---------------------------------------------------------------------------
local function reset()
    _translations = nil
    _loaded       = false
    logger.info("simpleui i18n: translation cache cleared")
end

return {
    translate = translate,
    ngettext  = ngettext,
    getLang   = detectLang,
    reset     = reset,
}
